fix: Improve exception message if dev server startup fails (#12847)
Earlier output in the browser and logs was:

```
com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Webpack exited prematurely
	at com.vaadin.flow.server.VaadinService.handleExceptionDuringRequest(VaadinService.java:1616)
```

Now it is
```
com.vaadin.flow.server.ServiceException: java.lang.IllegalStateException: Startup of Webpack failed. Output was:
[webpack-cli] Failed to load '/.../webpack.config.js' config
[webpack-cli] /.../webpack.config.js:1
(function (exports, require, module, __filename, __dirname) { f<>ail
                                                                ^

SyntaxError: Unexpected token '>'
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/Users/artur/test/fail-webpack23/node_modules/v8-compile-cache/v8-compile-cache.js:240:18)
    at Module._compile (/Users/artur/test/fail-webpack23/node_modules/v8-compile-cache/v8-compile-cache.js:184:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1149:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (/Users/artur/test/fail-webpack23/node_modules/v8-compile-cache/v8-compile-cache.js:159:20)
```

Fixes #12846