chore: added more covering tests to ComponentTest.java for covering getLocale() method (#16367)
* Added more covering tests to ComponentTest.java for the getLocale method. It was needed, because another external contributor PR is tackling
a refactor/optimization of this method (as well), and this change it will ensure the functionality, and execution branches are the same. (#16160)
* Fix typo/my bad in ComponentTest.java
* mvn formatter:format executed
* Locale.US is the first element of this list: List.of(Locale.US, Locale.CANADA_FRENCH);
 Not CANADA_FRENCH (night facepalm for myself)
 Should fix this error:
 "java.lang.AssertionError: First provided locale should be returned expected:<fr_CA> but was:<en_US>""
* Implemented @mcollovati review idea on creating provided locales.
Thank you ;)