fix: Ensure the correct version of commons-io is used by the plugin
Hopefully resolves

[ERROR] Failed to execute goal dev.hilla:hilla-maven-plugin:2.0.0.alpha5:prepare-frontend (default) on project starter-wizard: Execution default of goal dev.hilla:hilla-maven-plugin:2.0.0.alpha5:prepare-frontend failed: An API incompatibility was encountered while executing dev.hilla:hilla-maven-plugin:2.0.0.alpha5:prepare-frontend: java.lang.NoSuchMethodError: 'java.io.File org.apache.commons.io.FileUtils.delete(java.io.File)'