test: Run with web-test-runner instead of intern (#16093) (CP: 23.3) (#16117)
Use web-test-runner rather then intern, use a xhr mock that is esm compatible.
This should fix the 23.3 branch from failing build tests with this error:

Tunnel started
BUG: suiteEnd was received for invalid session
(ノಠ益ಠ)ノ彡┻━┻
Error: connect ECONNREFUSED ::1:4444