test: try to make test more stable by letting the server choose the port
Tests currently fail randomly with something like

java.lang.IllegalArgumentException: Tried to create a server on port 46159 but it was already in use
	at com.vaadin.base.devserver.WebpackHandlerTest.createStubWebpackTcpListener(WebpackHandlerTest.java:742)
	at com.vaadin.base.devserver.WebpackHandlerTest.prepareHttpServer(WebpackHandlerTest.java:725)
	at com.vaadin.base.devserver.WebpackHandlerTest.shouldNot_Handle_IndexHtmlInManifestPaths(WebpackHandlerTest.java:326)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
Caused by: java.net.BindException: Address already in use
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:74)
	at sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:100)
	at sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
	at sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
	at com.sun.net.httpserver.HttpServer.create(HttpServer.java:130)