Excluding osgi packages from serializable test to avoid any `NoClassDefFoundError` in validation of components that are not depend on OSGi. (#4815)
(cherry picked from commit 0e7239c12cc43b4c761fddb59ee56673d945dc09)