fix: Do not try to refresh app while it is initializing (#20504) (#20512)
When the app is bootstrapping, it only contains
`initializing`, `isActive` and `productionMode`. We should not call `sendEventMessage` at this point or might cause `Uncaught TypeError: l.sendEventMessage is not a function`. 

This is unlikely to happen in many real world scenarios but happens in Copilot tests

Co-authored-by: Artur <artur@vaadin.com>