fix: Fix failure when Vite sends many messages in sequence (#19340) (#19343)
Sending multiple messages at the same time resulted in

java.lang.IllegalStateException: The remote endpoint was in state [TEXT_FULL_WRITING] which is an invalid state for called method

which originates in calling `browserSession.getAsyncRemote().sendText` a second time before the complete callback for the first call has been called.

Now the getBasicRemote() method is used instead which blocks until the message has been sent.

Co-authored-by: Artur <artur@vaadin.com>